// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjqby5ZzopZUGF4B6eh1_ww9GErJspZ9c',
    appId: '1:716852000550:web:3d4e3e5d382f5f93a8b3e7',
    messagingSenderId: '716852000550',
    projectId: 'hris-pt-netizennetwork',
    authDomain: 'hris-pt-netizennetwork.firebaseapp.com',
    storageBucket: 'hris-pt-netizennetwork.appspot.com',
    measurementId: 'G-K8L3XWXRB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4_bmHfREiv5ABhKmpsRHt0TZUyaWoBSY',
    appId: '1:716852000550:android:a2a8a098fc8c2144a8b3e7',
    messagingSenderId: '716852000550',
    projectId: 'hris-pt-netizennetwork',
    storageBucket: 'hris-pt-netizennetwork.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeUL3w7_FWUEkao9d1kG9btBu5wnkqzxQ',
    appId: '1:716852000550:ios:3c84ba614844c3efa8b3e7',
    messagingSenderId: '716852000550',
    projectId: 'hris-pt-netizennetwork',
    storageBucket: 'hris-pt-netizennetwork.appspot.com',
    iosBundleId: 'com.example.hrisFirebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeUL3w7_FWUEkao9d1kG9btBu5wnkqzxQ',
    appId: '1:716852000550:ios:e3320e1e9b7c0ff2a8b3e7',
    messagingSenderId: '716852000550',
    projectId: 'hris-pt-netizennetwork',
    storageBucket: 'hris-pt-netizennetwork.appspot.com',
    iosBundleId: 'com.example.hrisFirebaseFlutter.RunnerTests',
  );
}
